### ISSUE TITLE
Error: Could not get managed heap of process . Most probably it is an unmanaged process.

### ISSUE THREAD

**Issue by GitPotTime** [Alois-xx/MemAnalyzer#1]
When i run the command MemAnalyzer.exe -pid {pid} from cmd, i get this error: `Error: Could not get managed heap of process . Most probably it is an unmanaged process.`

**Comment by Alois-xx** [comment]
Which .NET Runtime do you have in your process?

**Comment by Alois-xx** [comment]
Messenger did not respond to give more information. Closing.

**Comment by anilhdas** [comment]
@Alois-xx 
I'm observing the same error when I'm trying to analyze a C++ project (/std:c++14 with no CLR support).
Is this not supported?

![MemAnalyser issue](https://user-images.githubusercontent.com/19832987/212703892-fbc700c3-bd90-49e8-ad96-a8989f816cd7.png)

(I'm quite new to MemAnalyzer, so it's probable that I'm missing something important here. Would love to know).

**Comment by AloisKraus** [comment]
C++ is out of the scope of MemAnalyzer. It is meant for processes to track leaks which allocate on the managed heap of a .NET Runtime. Unmanaged heap leaks can be tracked with WPA and xperf. 

See https://learn.microsoft.com/en-us/windows-hardware/test/wpt/record-heap-snapshot for more information how you can use Heap Snapshots. There is also Heap Allocation profiling possible but that slows down your application normally down too much and it needs ca. 2 GB/minute of data which makes such huge datasets hard to analyze in WPA. 
For an example see: https://randomascii.wordpress.com/2019/10/27/heap-snapshots-tracing-all-heap-allocations/

An easier to use too is Performance HUD which should also be able to track Heap Memory leaks with just one click. 

https://www.microsoft.com/en-us/download/100813

It is a great tool for GDI/User object leaks and it should also work very well with C++ Heap Leaks: 

https://aloiskraus.wordpress.com/2020/07/20/ms-performance-hud-analyze-eventlog-reading-performance-in-realtime/
